FROM {{ image }}

ARG CODEDIR
ENV CODEDIR=$CODEDIR

RUN cd /tmp && wget http://dl-cdn.alpinelinux.org/alpine/v3.14/releases/aarch64/alpine-minirootfs-3.14.9-aarch64.tar.gz

COPY inittab /tmp/overlay/etc/inittab
COPY interfaces /tmp/overlay/etc/network/interfaces
COPY start.sh /tmp/overlay/start.sh
COPY resolv.conf /tmp/overlay/etc/resolv.conf
COPY entrypoint /entrypoint

WORKDIR $CODEDIR
RUN {{ install }} \
    && {{ build }}


CMD ["/bin/bash", "/entrypoint"]
