name: publish

on:
  release:
    types:
      - created

jobs:
  main:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: apt-get update
        run: sudo apt-get update -y

      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: "pyproject.toml"

      - name: install invoke
        run: pip install invoke

      - name: build
        run: inv build

      - name: publish
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        run: inv publish

      - name: get latest tag
        id: latest_tag
        run: |
          LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "latest_tag=${LATEST_TAG}" >> $GITHUB_OUTPUT

      - name: set up qemu
        uses: docker/setup-qemu-action@v2
        with:
          platforms: "linux/arm64/v8"

      - name: docker build
        uses: docker/build-push-action@v3
        with:
          push: false
          platforms: "linux/arm64/v8"
          tags: ghcr.io/${{ github.repository }}:latest

      - name: docker tag
        run: inv docker-tag --dst-tag ${{ steps.latest_tag.outputs.latest_tag }}

      - name: docker-push
        env:
          CR_PAT: ${{ secrets.CR_PAT }}
          GH_USERNAME: ${{ secrets.GH_USERNAME }}
        run: |
          echo ${{ env.CR_PAT }} | docker login ghcr.io -u ${{ env.GH_USERNAME }} --password-stdin
          inv docker-push
          inv docker-push --tag ${{ steps.latest_tag.outputs.latest_tag }}
